"""Stable control-layer contracts shared by JL integrations."""

from .approvals import (
    ApprovalError,
    ApprovalRecord,
    ApprovalState,
    OneTimeApprovalStore,
)
from .auth import (
    AuthenticatedRequestHandler,
    CredentialError,
    CredentialProvider,
    FileCredentialProvider,
)
from .control_plane import (
    ControlPathResult,
    ControlPlaneError,
    ControlRequest,
    HermesInvocationProjection,
    JLControlPlane,
)
from .health import HealthAssessment, HealthMonitor, ProbeOutcome
from .hermes_projection import (
    HermesIdentity,
    HermesProjection,
    HermesProjectionError,
    HermesProjectionResult,
)
from .ipc import (
    DEFAULT_MAX_REQUEST_BYTES,
    DEFAULT_TIMEOUT_SECONDS,
    PROTOCOL_VERSION,
    IPCError,
    IPCProtocolError,
    IPCRequestEnvelope,
    IPCResponseEnvelope,
    IPCStartupError,
    UnixSocketServer,
    send_request,
)
from .permissions import (
    ActionClass,
    ActionProposal,
    DecisionOutcome,
    PermissionDecision,
    PermissionRiskEngine,
)
from .registry import (
    CapabilityDescriptor,
    CapabilityRegistry,
    CapabilityType,
    ConfigurationRequirements,
    Entrypoint,
    EntrypointKind,
    Health,
    HealthState,
    RegistryValidationError,
    Source,
)
from .request_state import (
    IllegalRequestTransition,
    RequestLifecycle,
    RequestState,
    SecureControlRequestHandler,
)
from .router import (
    CostClass,
    DeterministicModelRouter,
    ModelCandidate,
    RejectedCandidate,
    RouteDecision,
    RouteRequest,
    RouterPolicy,
    RoutingError,
    TaskCategory,
)

__all__ = [
    "ActionClass",
    "ActionProposal",
    "ApprovalError",
    "ApprovalRecord",
    "ApprovalState",
    "AuthenticatedRequestHandler",
    "CapabilityDescriptor",
    "CapabilityRegistry",
    "CapabilityType",
    "ConfigurationRequirements",
    "ControlPathResult",
    "ControlPlaneError",
    "ControlRequest",
    "CostClass",
    "CredentialError",
    "CredentialProvider",
    "DEFAULT_MAX_REQUEST_BYTES",
    "DEFAULT_TIMEOUT_SECONDS",
    "DecisionOutcome",
    "DeterministicModelRouter",
    "Entrypoint",
    "EntrypointKind",
    "Health",
    "HealthAssessment",
    "HealthMonitor",
    "HealthState",
    "HermesIdentity",
    "HermesInvocationProjection",
    "HermesProjection",
    "HermesProjectionError",
    "HermesProjectionResult",
    "IPCError",
    "IPCProtocolError",
    "IPCRequestEnvelope",
    "IPCResponseEnvelope",
    "IPCStartupError",
    "IllegalRequestTransition",
    "JLControlPlane",
    "FileCredentialProvider",
    "ModelCandidate",
    "OneTimeApprovalStore",
    "PROTOCOL_VERSION",
    "ProbeOutcome",
    "PermissionDecision",
    "PermissionRiskEngine",
    "RegistryValidationError",
    "RejectedCandidate",
    "RequestLifecycle",
    "RequestState",
    "RouteDecision",
    "RouteRequest",
    "RouterPolicy",
    "RoutingError",
    "SecureControlRequestHandler",
    "Source",
    "TaskCategory",
    "UnixSocketServer",
    "send_request",
]
